### ISSUE TITLE
Could you provide the code on EDAM?

### ISSUE THREAD

**Issue by Italy2006** [zhaozhengChen/LPCAM#6]
Thanks for your work! I want to compare my work with yours on EDAM and MCTformer, but i  find that your paper provide the result of EDAM on coco dataset but the original paper doesn't. So can you provide the corresponding code? Looking forward to your reply！

**Comment by zhaozhengChen** [comment]
I apologize for the delayed response.

In our paper, the EDAM+LPCAM result refers to using the post-processing method (saliency map) from EDAM to refine the mask generated by LPCAM.

If you still need the code, please let me know. I will locate and provide it for you.

Once again, I'm sorry for any inconvenience caused by my late reply.

**Comment by Italy2006** [comment]
> I apologize for the delayed response.
> 
> In our paper, the EDAM+LPCAM result refers to using the post-processing method (saliency map) from EDAM to refine the mask generated by LPCAM.
> 
> If you still need the code, please let me know. I will locate and provide it for you.
> 
> Once again, I'm sorry for any inconvenience caused by my late reply.

Thank you for your reply and it doesn't matter, i have solved this problem。 But ihave another questions about the code on the MCTformer, could you provide for it?
